# Generated by Django 4.1.3 on 2023-02-11 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse', models.CharField(blank=True, max_length=100, null=True)),
                ('first_child', models.CharField(blank=True, max_length=100, null=True)),
                ('second_child', models.CharField(blank=True, max_length=100, null=True)),
                ('third_child', models.CharField(blank=True, max_length=100, null=True)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_purpose', models.TextField(blank=True, max_length=500, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('departure_location', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
